pipeline {
    agent none

    stages {
        stage('Build base image') {
            agent {
                docker {
                    image 'echo'
                }
            }
            steps {
                sh 'echo "Hello Jenkins"'
            }
        }
    }
}