pipeline {
    agent none

    stages {
        stage('Precheck') {
            agent any 
            environment {
                MY_ENV = 'my_env'
            }
            steps {
                sh 'echo "#${env.BUILD_NUM} Running ${env.BUILD_ID} on ${env.JENKINS_URL}"'
                sh 'echo "${env.MY_ENV}"'
            }
        }

        stage('Build image') {
            agent any
            steps {
                sh 'docker build -t 176.122.188.100:16000/test .'
            }
        }

        stage('Push image') {
            agent any
            steps {
                sh 'docker push 176.122.188.100:16000/test:latest'
            }
        }
    }
}